apiVersion: 1

deleteDatasources:
  - name: WRT1900ACS
    orgId: 1

datasources:
- name: WRT1900ACS
  type: influxdb
  access: proxy
  url: https://myst:8086
  password:root
  user:root
  database: WRT1900ACS
  basicAuth: false
  basicAuthUser:
  basicAuthPassword:
  withCredentials:
  isDefault: true
  jsonData:
     tlsAuth: false
     tlsAuthWithCACert: false
  secureJsonData:
    tlsCACert: ""
    tlsClientCert: ""
    tlsClientKey: ""
  version: 1
  editable: true
