{
 "title": "Network Interface Stats",
 "description": "Templated dashboard which provides an overview for your router/switch ports and detailed traffic statistics.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "custominterval",
    "query": "1m,2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "host",
    "query": "SHOW TAG VALUES FROM interface WITH KEY = \"agent_host\""
   },
   {
    "name": "interface",
    "query": "SHOW TAG VALUES FROM interface WITH KEY = \"ifDescr\" WHERE agent_host=~ /$host$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Interface summary",
   "type": "table",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ifDescr" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "interface",
     "select": [
      [
       { "params": [ "ifOperStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "ifOperStatus" ], "type": "alias" }
      ],
      [
       { "params": [ "ifInDiscards" ], "type": "field" }
      ],
      [
       { "params": [ "ifInErrors" ], "type": "field" }
      ],
      [
       { "params": [ "ifInOctets" ], "type": "field" }
      ],
      [
       { "params": [ "ifInUcastPkts" ], "type": "field" }
      ],
      [
       { "params": [ "ifMtu" ], "type": "field" }
      ],
      [
       { "params": [ "ifOutErrors" ], "type": "field" }
      ],
      [
       { "params": [ "ifOutDiscards" ], "type": "field" }
      ],
      [
       { "params": [ "ifSpeed" ], "type": "field" }
      ],
      [
       { "params": [ "ifPhysAddress" ], "type": "field" }
      ],
      [
       { "params": [ "ifLastChange" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Total traffic in $interface", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "$interface in",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 12 },
   "repeat": "interface",
   "format": "bytes",
   "valueName": "total",
   "targets": [
    {
     "measurement": "interface_rx_wrt",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "if_octets" }
     ]
    }
   ]
  },
  { "title": "Total traffic out $interface", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "$interface out",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 15 },
   "repeat": "interface",
   "format": "bytes",
   "valueName": "total",
   "targets": [
    {
     "measurement": "interface_tx_wrt",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "if_octets" }
     ]
    }
   ]
  },
  { "title": "Throughput $interface", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Throughput $interface",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "repeat": "interface",
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$interface $col",
     "groupBy": [
      { "params": [ "$custominterval" ], "type": "time" },
      { "params": [ "/^$interface$/" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interface_tx_wrt",
     "query": "SELECT non_negative_derivative(mean(\"value\"), 1s) *8 AS \"out\" FROM \"interface_tx_wrt\" WHERE $timeFilter GROUP BY time($custominterval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "out" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$interface $col",
     "groupBy": [
      { "params": [ "$custominterval" ], "type": "time" },
      { "params": [ "/^$interface$/" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interface_rx_wrt",
     "query": "SELECT non_negative_derivative(mean(\"value\"), 1s) *8 AS \"out\" FROM \"interface_tx_wrt\" WHERE $timeFilter GROUP BY time($custominterval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "in" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}